// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTLvvWvmUPC15eqyYheLqGE4WKczYpqfI',
    appId: '1:358263927947:web:c46270d81ef46fba9c108e',
    messagingSenderId: '358263927947',
    projectId: 'steep-6cd0f',
    authDomain: 'steep-6cd0f.firebaseapp.com',
    storageBucket: 'steep-6cd0f.firebasestorage.app',
    measurementId: 'G-D7RLBQE7S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvEAD07mpkIDgE0FvVc7l4xveRAivp4c',
    appId: '1:358263927947:android:e4376057d2fca9189c108e',
    messagingSenderId: '358263927947',
    projectId: 'steep-6cd0f',
    storageBucket: 'steep-6cd0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cVCcO7WB9qhOfEFS7GWEVsu0OAcGPkU',
    appId: '1:358263927947:ios:f44ae8a9270588a19c108e',
    messagingSenderId: '358263927947',
    projectId: 'steep-6cd0f',
    storageBucket: 'steep-6cd0f.firebasestorage.app',
    iosBundleId: 'com.example.steep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cVCcO7WB9qhOfEFS7GWEVsu0OAcGPkU',
    appId: '1:358263927947:ios:f44ae8a9270588a19c108e',
    messagingSenderId: '358263927947',
    projectId: 'steep-6cd0f',
    storageBucket: 'steep-6cd0f.firebasestorage.app',
    iosBundleId: 'com.example.steep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTLvvWvmUPC15eqyYheLqGE4WKczYpqfI',
    appId: '1:358263927947:web:b8732cea03eca8d09c108e',
    messagingSenderId: '358263927947',
    projectId: 'steep-6cd0f',
    authDomain: 'steep-6cd0f.firebaseapp.com',
    storageBucket: 'steep-6cd0f.firebasestorage.app',
    measurementId: 'G-9TTX0ELMEE',
  );
}
